language: go

go:
  - 1.10.x


cache:
  directories:
    ${TRAVIS_BUILD_DIR}/vendor
    ${HOME}/.glide

addons:
  apt:
    sources:
      - sourceline: ppa:masterminds/glide
    packages:
      - glide

install:
  - git clone https://github.com/copernet/secp256k1.git /tmp/secp256k1
  - pushd /tmp/secp256k1
  - ./autogen.sh
  - ./configure --enable-experimental --enable-module-ecdh --enable-module-recovery
  - make -j16
  - sudo make install
  - cd -

  - glide install
  - cd secp256k1
  - go test -v


after_script:
 - go get github.com/mattn/goveralls
 - make coverage-concat
 - $HOME/gopath/bin/goveralls -coverprofile=coverage/full -service=travis-ci
